<?php

/** @var \App\Components\Plates\Template $this */

?>
<header>
    <div><img src="/pet/didi-dog/digi-dog.jpg" alt="Logo" class="img-fluid"></div>
    <h1>Ветеринарная клиника Didi-Dog</h1>
</header>

<p>Ветеринарная клиника, основанная семьёй из Петербурга. Главный врач Кандидат ветеринарных наук Дмитрий Сергеев. Главный хирург Татьяна Филатова – врач со стажем 26 лет. Клиника предлагает широкий спектр медицинских и косметологических услуг: анализы крови, УЗИ, рентген, стерилизацию, вакцинацию, хирургические операции, груминг. Цены <a href="https://dididog.net/price/rus">представлены</a> на сайте.</p>

<?= $this->fetch('place-brief', [
    'address' => 'Didi Dighomi, III M/D, 20',
    'yandexLink' => 'https://yandex.ru/profile/80391151410',
    'googleLink' => 'https://goo.gl/maps/w1W55f8Rqw3Viy3j7',
    'links' => [
        ['https://dididog.net/home/rus', 'dididog.net'],
        ['https://facebook.com/DidiDog23', 'facebook.com/DidiDog23'],
    ],
    'workHours' => 'Ежедневно 12:00 -- 20:00',
    'phones' => [
        '5 111 24 0 27',
    ],
]) ?>

<?= $this->fetch('gallery', [
    'path' => preg_replace('/^source::/', '', $this->name->getName()),
    'gallery' => 'gallery',
]) ?>
