<?php

/** @var \App\Components\Plates\Template $this */

?>
<header>
    <h1>Пивной сад</h1>
</header>

<p>Нет информации. Похоже это какой-то пивной магазин-бар.</p>

<?= $this->fetch('place-brief', [
    'address' => 'ул. Царя Мириана, 37А',
    'yandexLink' => 'https://yandex.com.ge/maps/-/CLs3q7S',
    'googleLink' => 'https://goo.gl/maps/MB1eytHGBkznfgsL8',
    'links' => [
    ],
    'workHours' => 'Ежедневно', // TODO: Когда именно?
    'phones' => [
    ],
]) ?>

<?= $this->fetch('gallery', [
    'path' => preg_replace('/^source::/', '', $this->name->getName()),
    'gallery' => 'gallery',
]) ?>
