<?php

/** @var \App\Components\Plates\Template $this */

?>
<header>
    <h1>Бар / бургерная Good choice</h1>

</header>

<p>В меню бургеры, хотдоги, картофель фри, пиво (неразливное), безалкогольные напитки. Персонал говорит по-английски и по-русски немного, оплата наличными и картой. Столики внутри и на улице. Есть доставка Wolt и Glovo.</p>
<p></p>

<?= $this->fetch('place-brief', [
    'address' => 'ул. Георгия Брцкинвале, 32',
    'yandexLink' => 'https://yandex.com.ge/maps/-/CCUDBIRXDA',
    'googleLink' => 'https://maps.app.goo.gl/Jyz5UQh8p3WR6Ps19',
    'links' => [
    ],
    'workHours' => 'Ежедневно 11:00 -- 03:00',
    'phones' => [
        '596 90 74 74',
    ],
]) ?>

<?= $this->fetch('gallery', [
    'path' => preg_replace('/^source::/', '', $this->name->getName()),
    'gallery' => 'gallery',
]) ?>
