<?php

/** @var \App\Components\Plates\Template $this */

?>
<header>
    <h1>Gourmet Garden Shawarma</h1>
</header>

<p>Просто отличная шаурмичная. Часть работников понимает по-русски. Здесь готовят классическую шаурму с мясом из донер-печи. На выбор: курица, свинина или микс. Средняя шаурма стоит 12 лари. Можно забрать с собой или поесть за одним из трёх столиков в помещении, рассчитанных на 3-4 человека каждый. Летом работает кондиционер. Есть туалетная комната.</p>

<p>Помимо шаурмы здесь можно заказать бургер, хот-дог, картошку фри, куриные крылья. Только хот-дог идёт в большой булке, очень много хлеба.</p>

<p>Ещё за 15 лари здесь можно заказать <a href="food/gourmet-garden/2023-07-07%2016-11-06.JPG" data-fancybox>тарелку</a> с ингредиентами шаурмы без лаваша, но с картошкой фри.</p>

<?= $this->fetch('place-brief', [
    'address' => 'ул. Иоанэ Петрици, 14А',
    'yandexLink' => 'https://yandex.com.ge/maps/-/CCUDI4x~PB',
    'googleLink' => 'https://goo.gl/maps/3vSvzrzQfSHn8HXM7',
    'links' => [
        ['https://www.facebook.com/gourmetgarden.ge', 'facebook.com/gourmetgarden.ge', 'правда чё-то перестал работать'],
    ],
    'workHours' => 'Ежедневно 11:00 -- 01:00',
    'phones' => [
        '596 309 309',
    ],
]) ?>

<?= $this->fetch('gallery', [
    'path' => preg_replace('/^source::/', '', $this->name->getName()),
    'gallery' => 'gallery',
]) ?>
