<?php

/** @var \App\Components\Plates\Template $this */

?>
<header>
    <h1>Кафе MillCo <img src="https://millco.kovzy.com/media/2022.08.30_12.39.18_RBROd0LS_logo.png" alt="Logo" style="width: 60px; display: inline; margin-top: -50px;"></h1>
</header>

<p>Популярное кафе. Владелец говорит по-русски, официанты понимают по-английски. Есть столики внутри и снаружи, можно приходить поработать с ноутбуком.</p>
<p>Хозяин кафе &mdash; владелец сети <a href="https://chainikoff.ru/">Чайникофф</a>. С удовольствием расскажет откуда они привозят зёрна, как сами их обжаривают и почему именно у них получается вкусный кофе. 🙂</p>
<p>Помимо кофе и сладостей, кафе предлагает завтраки, салаты, горячие блюда, алкогольные и безалкогольные напитки.</p>

<?= $this->fetch('place-brief', [
    'address' => 'ул. Георгия Брцкинвале, 32',
    'yandexLink' => 'https://yandex.com.ge/maps/-/CCUDQAboWA',
    'googleLink' => 'https://goo.gl/maps/NxEoeACWKxHRrkgB7',
    'links' => [
        ['https://www.facebook.com/MillCo.Coffee/', 'facebook.com/MillCo.Coffee/'],
        ['https://www.instagram.com/millco_coffee/', 'instagram.com/millco_coffee/'],
        ['https://millco.kovzy.com/?lang=4', 'millco.kovzy.com'],
    ],
    'workHours' => 'Пн-Пт: 10:00 -- 22:00, Сб-Вс: 11:00 -- 22:00',
    'phones' => [
        '511 16 64 44',
    ],
]) ?>

<?= $this->fetch('gallery', [
    'path' => preg_replace('/^source::/', '', $this->name->getName()),
    'gallery' => 'gallery',
]) ?>
