<?php

/** @var \App\Components\Plates\Template $this */

?>
<header>
  <h1>Шаурмичная New Meat</h1>
</header>

<p>Раньше здесь была шаурмичная &laquo;Mix-Meat&raquo;, которая пользовалась популярностью. Но где-то в апреле 2023 она закрылась на реконструкцию и сейчас открылась под названием &laquo;New Meat&raquo;. Но отзывов о ней пока нет.</p>

<?= $this->fetch('place-brief', [
    'address' => 'ул. Царя Мириана, 56',
    'yandexLink' => 'https://yandex.com.ge/maps/-/CCUDIJxiXC',
    'googleLink' => 'https://maps.app.goo.gl/fN1XhHnkNfDfdSbK9',
    'links' => [
        ['https://www.facebook.com/Chvenisufrakartuli', 'facebook.com/Chvenisufrakartuli'],
    ],
    'workHours' => 'Ежедневно 10:00 -- 22:00',
    'phones' => [
        '598 56 81 81',
    ],
]) ?>

<?= $this->fetch('gallery', [
    'path' => preg_replace('/^source::/', '', $this->name->getName()),
    'gallery' => 'gallery',
]) ?>

<h2>Меню</h2>
<?= $this->fetch('gallery', [
    'path' => preg_replace('/^source::/', '', $this->name->getName()),
    'gallery' => 'menu',
]) ?>
