<?php

/** @var \App\Components\Plates\Template $this */

?>
<header>
  <h1>Кафе &laquo;Наш стол — грузинская кухня&raquo;</h1>
    <div style="color: #999; font-style: italic; margin-top: -15px;">(прежде ошибочно называлось &laquo;New Meat&raquo; из-за того, что на вывеске так было написано по-английски)</div>
</header>

<p>Неплохое уличное кафе. Здесь можно заказать шашлык, люля-кебаб, различные салаты, супы (будьте осторожны, суп может быть острый). Можно поесть как внутри помещения, так и за столиком на улице. Цены весьма умеренные. В кафе работает семейная пара: муж и жена, которые прекрасно говорят по-русски. Раньше здесь можно было заказать шаурму с мясом из шашлыка, но сейчас они её убрали из меню.</p>

<p>Помимо готовой еды, здесь можно купить их собственные полуфабрикаты, чтобы дома самостоятельно пожарить котлеты или кебаб. Получается очень вкусно и дешевле, чем в кафе. Например, 1 сырой кебаб стоит всего 3 лари.</p>

<?= $this->fetch('place-brief', [
    'address' => 'ул. Царя Мириана, 56',
    'yandexLink' => 'https://yandex.com.ge/maps/-/CCUDIJxiXC',
    'googleLink' => 'https://maps.app.goo.gl/fN1XhHnkNfDfdSbK9',
    'links' => [
        ['https://www.facebook.com/Chvenisufrakartuli', 'facebook.com/Chvenisufrakartuli'],
    ],
    'workHours' => 'Ежедневно 10:00 -- 22:00',
    'phones' => [
        '598 56 81 81',
    ],
]) ?>

<?= $this->fetch('gallery', [
    'path' => preg_replace('/^source::/', '', $this->name->getName()),
    'gallery' => 'gallery',
]) ?>

<h2>Меню</h2>
<?= $this->fetch('gallery', [
    'path' => preg_replace('/^source::/', '', $this->name->getName()),
    'gallery' => 'menu',
]) ?>
