<?php

/** @var \App\Components\Plates\Template $this */
/** @var \App\Components\Plates\MetaContainer $meta */

$meta->addKeywords([
    'копии ключей',
    'дубликаты ключей',
    'ключи',
    'скопировать ключ',
]);

?>
<header>
    <h1>Изготовление копий ключей</h1>
</header>

<p>Небольшой киоск, где можно заказать изготовление ключей. Там всегда один и тот же мастер, работает каждый день без выходных. Мастер порядочный и хорошо говорит по-русски. Видимо, чтобы ему не было скучно торчать там каждый день, в киоске постоянно есть другие люди, которые там не работают. Скорее всего это друзья мастера. Изготовление дубликата одного простого (плоского) ключа стоит 7 лари. Оплата только наличными.</p>

<?= $this->fetch('place-brief', [
    'address' => 'улица Иоанэ Петрици, 8А',
    'yandexLink' => 'https://yandex.com.ge/maps/-/CDaGA6mS',
    'googleLink' => 'https://maps.app.goo.gl/LGcmPVbBVUUCQ9iu7',
    'links' => [
    ],
    'workHours' => 'Ежедневно 9:00 -- 19:00 (иногда даже дольше)',
    'phones' => [
        '591 941 518',
    ],
]) ?>

<?= $this->fetch('gallery', [
    'path' => preg_replace('/^source::/', '', $this->name->getName()),
    'gallery' => 'gallery',
]) ?>
