<?php

/** @var \App\Components\Plates\Template $this */
/** @var string $title */

?>
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $this->escape($title); ?></title>
    <link rel="icon" type="image/svg+xml" href="/favicon.svg">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="/site.css" rel="stylesheet">
    <!-- FancyApps image viewer -->
    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css" />
</head>
<body>
    <header>
        <hgroup>
            <h1><a href="/">Диди Дигоми, Тбилиси</a></h1>
            <h2>Краткий путеводитель по району от создателей <a href="https://t.me/dihomi" target="_blank">телеграм-чатика</a></h2>
        </hgroup>
    </header>
    <section id="main">
        <nav>
            <a href="/">&larr; Главная</a>
        </nav>
        <article>
<?= $this->section('content') ?>
        </article>
    </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script>Fancybox.bind("[data-fancybox]", {});</script>
</body>
</html>
