<h3>Где поесть или выпить</h3>
<section class="places">
    <section>
        <a href="/food/gourmet-garden.html">
            <img src="/food/gourmet-garden/preview.jpg" class="img-fluid" alt="Preview">
            Gourmet Garden Shawarma
        </a>
    </section>

    <section>
        <a href="/food/samepo-shawarma.html">
            <img src="/food/samepo-shawarma/preview.jpg" class="img-fluid" alt="Preview">
            Самэпо шаурма
        </a>
    </section>

    <section>
        <a href="/food/shaurmaclub.html">
            <img src="/food/shaurmaclub/preview.jpg" class="img-fluid" alt="Preview">
            Shaurma Club
        </a>
    </section>

    <section>
        <a href="/food/millco.html">
            <img src="/food/millco/preview.jpg" class="img-fluid" alt="Preview">
            Кафе MillCo
        </a>
    </section>

    <section>
        <a href="/food/good-choice.html">
            <img src="/food/good-choice/preview.jpg" class="img-fluid" alt="Preview">
            Бар / бургерная Good choice
        </a>
    </section>

    <section>
        <a href="/food/beer-garden.html">
            <img src="/food/beer-garden/preview.jpg" class="img-fluid" alt="Preview">
            Пивной сад
        </a>
    </section>

    <section>
        <a href="/food/foody.html">
            <img src="/food/foody/preview.jpg" class="img-fluid" alt="Preview">
            Доставка еды FOODY
        </a>
    </section>
</section>

<h3>Магазины</h3>
<section class="places">
    <section>
        <a href="/grocery/green-market.html">
            <img src="/grocery/green-market/preview.jpg" class="img-fluid" alt="Preview">
            Продуктовый магазин Green Market
        </a>
    </section>

    <section>
        <a href="/grocery/sufra.html">
            <img src="/grocery/sufra/preview.jpg" class="img-fluid" alt="Preview">
            Мясная лавка Sufra
        </a>
    </section>
</section>

<h3>Занятия спортом</h3>
<section class="places">
    <section>
        <a href="/sport/tonus-gym.html">
            <img src="/sport/tonus-gym/preview.jpg" class="img-fluid" alt="Preview">
            Тренажёрный зал Tonus Gym
        </a>
    </section>

    <section>
        <a href="/sport/gaguagym.html">
            <img src="/sport/gaguagym/preview.jpg" class="img-fluid" alt="Preview">
            Тренажёрный зал Gagua Gym
        </a>
    </section>
</section>

<h3>Домашние животные</h3>

<section class="places">
    <section>
        <a href="/pet/didi-dog.html">
            <img src="/pet/didi-dog/preview.jpg" class="img-fluid" alt="Preview">
            Ветеринарная клиника Didi Dog
        </a>
    </section>

    <section>
        <a href="/pet/pet-boarding.html">
            <img src="/pet/pet-boarding/preview.jpg" class="img-fluid" alt="Preview">
            Передержка для собаки
        </a>
    </section>
</section>

<h4>Зоо-магазины:</h4>
<section class="places">
    <section>
        <a href="/pet/zoolife.html">
            <img src="/pet/zoolife/preview.jpg" class="img-fluid" alt="Preview">
            Магазин ZooLife
        </a>
    </section>

    <section>
        <a href="/pet/zoocity.html">
            <img src="/pet/zoocity/preview.jpg" class="img-fluid" alt="Preview">
            Магазин ZooCity
        </a>
    </section>

    <section>
        <a href="/pet/zoomart.html">
            <img src="/pet/zoomart/preview.jpg" class="img-fluid" alt="Preview">
            Магазин ZooMart
        </a>
    </section>
</section>

<!--    <h3>Парикмахерские, салоны красоты</h3>-->

<h3>Прочее</h3>

<section class="places">
    <section>
        <a href="/laundry/pero.html">
            <img src="/laundry/pero/preview.jpg" class="img-fluid" alt="Preview">
            Прачечная/химчистка &quot;Pero&quot;
        </a>
    </section>

    <section>
        <a href="/electronics/pc-room.html">
            <img src="/electronics/pc-room/preview.jpg" class="img-fluid" alt="Preview">
            Компьютерный магазин PC Room
        </a>
    </section>

    <section>
        <a href="/building/hardware-store.html">
            <img src="/building/hardware-store/preview.jpg" class="img-fluid" alt="Preview">
            Строительные материалы
        </a>
    </section>

    <section>
        <a href="/service/duplicate-keys.html">
            <img src="/service/duplicate-keys/preview.jpg" class="img-fluid" alt="Preview">
            Дубликаты ключей
        </a>
    </section>

    <section>
        <a href="/gift/indi-bazari.html">
            <img src="/gift/indi-bazari/preview.jpg" class="img-fluid" alt="Preview">
            Indi Bazari
        </a>
    </section>

    <section>
        <a href="/education/cybertron.html">
            <img src="/education/cybertron/preview.jpg" class="img-fluid" alt="Preview">
            Клуб робототехники Кибертрон
        </a>
    </section>
</section>

<h3>Частные услуги</h3>

<section class="places">
    <section>
        <a href="/service/sabrie-cosmo.html">
            <img src="/service/sabrie-cosmo/preview.jpg" class="img-fluid" alt="Preview">
            Услуги косметолога от Sabrie
        </a>
    </section>

    <section>
        <a href="/service/mimicraft.html">
            <img src="/service/mimicraft/preview.jpg" class="img-fluid" alt="Preview">
            Изделия ручной работы из дерева, гипса и кожи
        </a>
    </section>
</section>
